on: [push, pull_request]
name: Build and push to Dockerhub
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git sha
      uses: benjlevesque/short-sha@v2.1
      id: git-sha
      with:
        length: 8
    
    - name: Checkout code with submodules
      uses: actions/checkout@v2      

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./UdpPlugSimulator/Dockerfile
        no-cache: true
        push: true
        tags: oesinc/plug-simulator:latest,oesinc/plug-simulator:${{ steps.git-sha.outputs.sha }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}


